### PR TITLE
Update the gitignore to include compiled files

### PR DESCRIPTION
**Pull request by bmintz**

### CODE REVIEW

**Comment by cathugger** [comment]
tbh idk, it's not like I accidentally not include them in the first place.
there aint a lot of them so I just manually ignore them, .o and .onion ones are pretty genetic while explicitly excluding autoconf stuff imo isnt worth it. I prefer gitignore being clean.

**Comment by bmintz** [comment]
i don't personally understand your position here, i think gitignore is for ignoring shit so it shouldn't matter what you put in it. If you want I can document the gitignore with comments, idk if that'd make it cleaner.
My shell prompt shows me whether there are any untracked, unstaged, and committed files so, since I don't `cat .gitignore` very often, I think the tradeoff is worth it.

**Comment by cathugger** [comment]
@bmintz https://github.com/cathugger/mkp224o/commit/c65672193ff3dad2229bddbd4cb1201d909c0468
hopefully this should be ok

**Comment by bmintz** [comment]
btw you can commit to the branch on my PR unless i uncheck "allow edits from contributors"

**Pull request closed without merging**
