### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EsmailELBoBDev2**
while compiling i got error and this solved it
https://superuser.com/questions/1248542/checking-whether-the-c-compiler-works-no

### CODE REVIEW

**Comment by cathugger** [comment]
which distro / version?
what exactly was an error message?
which exact mkp224o version you were testing with?
did you try installing g++ instead of gobjc++? GNU Objective-C++ compiler looks kinda irrelevant at all for this so I suspect it's some dependency of it which gets pulled in and makes things work..
but with current information you've provided i can't neither reproduce whether this issue really exists & really get fixed by PR you've provided, nor improve it.

**Comment by EsmailELBoBDev2** [comment]
> which distro / version? what exactly was an error message? which exact mkp224o version you were testing with? did you try installing g++ instead of gobjc++? GNU Objective-C++ compiler looks kinda irrelevant at all for this so I suspect it's some dependency of it which gets pulled in and makes things work.. but with current information you've provided i can't neither reproduce whether this issue really exists & really get fixed by PR you've provided, nor improve it.

Debian 11 and I do not really remember the error message, but I remember it got solved by installing `gobjc++`
and error message is near from: 
```
checking whether the C compiler works... no
configure: error: C compiler cannot create executables
See 'config.log' for more details
```

**Comment by cathugger** [comment]
I've installed fresh debian container with debootstrap and installed deps as documented and everything worked.
then I've tried uninstalling them, and installing with `--no-install-recommends`, and configure failed.
inspecting error log, what i saw was:
```
configure:2213: gcc    conftest.c  >&5
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
collect2: error: ld returned 1 exit status
```
and installing `libc6-dev` fixed that.. so I guess I can add `libc6-dev` to requirements for systems where `--no-install-recommends` is the user-configured default.
note that `libc6-dev` is also included when one tries to install `gobjc++`.

**Comment by cathugger** [comment]
should be fixed by https://github.com/cathugger/mkp224o/commit/d202229a437d98b874f0ecc4affcf58f65596802

**Comment by EsmailELBoBDev2** [comment]
Well, I guess it's close time!

**Pull request closed without merging**
