### PR TITLE
Add checkpointing support for passphrases

### LINKED ISSUE #59: [Feature request] To Pause and Resume
To Pause and Resume the sessions (like hashcat)

### PR DESCRIPTION
**Pull request by scribblemaniac**
When using a passphrase, with these changes you can add `-c filename` to the arguments and the program will occasionally write a "checkpoint" to that file. Then when you restart the program with the same passphrase and checkpoint file, it will read the checkpoint data and avoid rechecking the same keys checked last time the program was run. Knowing what's in the checkpoint file does not directly compromise either the passphrase, seed, or generated private keys because the data in the checkpoint file is effectively the increments to the seed. However it would make it easier to brute-force the passphrase by giving an upper-bound on the number of keys checked.

Closes #59

### CODE REVIEW

**Comment by cathugger** [comment]
my head is still fucked so i prolly wont think about this much soon but ive noticed some wrong stuff about this

first of all i think it shouldn't really need separate checkpoint variable. maintaining two of them will decrease performance. like i said didn't think of this much so not sure if thats doable in another way or not.
secondly, it should probably save state only upon receiving ctrl+c or sigterm. that will probably fit the most use cases, and will reduce fopens/fwrites/fcloses which are pretty slow operations.
oh also current code performs fopens/fwrites/fcloses outside of mutex, which isn't thread safe and may result in undesired rewrites.
not to mention that it should probably be using atomic write/sync/rename sequence.
also this should probably be long option, reserving '-c' for this feels kinda wrong.

**Comment by scribblemaniac** [comment]
> first of all i think it shouldn't really need separate checkpoint variable. maintaining two of them will decrease performance. like i said didn't think of this much so not sure if thats doable in another way or not.

There are at least two alternative ways you could do this: 1. You could write determseed directly to the file. This would be terrible for security because it would be basically the equivalent of writing the passphrase to the disk. 2. You could calculate the same checkpoint value by subtracting the current determseed value from the original determseed value. However this is significantly more complex with a byte array than simply performing the same increment operation that is already being done. More importantly though, the performance impact is insignificant. As it stands now, it is doing one increment operator per *restart* of the worker (for me that happens less than once per second assuming a non-trivial search term). Even with it doing the far slower file write operation each of those times, I saw no significant difference in performance after these changes.

> secondly, it should probably save state only upon receiving ctrl+c or sigterm. that will probably fit the most use cases, and will reduce fopens/fwrites/fcloses which are pretty slow operations.

That's not a bad idea. I think it writes a little too often right now, and it's probably a worse issue for people with slower file systems of faster cpus than me. I did it this way primarily because it was simple and worked well in my testing. However I think it should still write out a checkpoint file occasionally even you catch the signal, because if the program crashes or is killed or your computer shuts down, I would expect that when I enable a checkpoint feature, it would save at least some of my progress in these cases.

> oh also current code performs fopens/fwrites/fcloses outside of mutex, which isn't thread safe and may result in undesired rewrites.
not to mention that it should probably be using atomic write/sync/rename sequence.

Yes :+1: 

> also this should probably be long option, reserving '-c' for this feels kinda wrong.

Are you planning on adding many new arguments for more important features? Do you guarantee backwards compatibility for the CLI in future releases? It seems like an unnecessary thing to worry about for a utility like this where: a) there isn't much planned or actively under development and b) it shouldn't be an issue to change the CLI behavior in the future if you do add something else which you want to use -c for. But if you want to use a long argument right now that's fine with me. I don't expect it to be a very commonly used feature.

**Comment by cathugger** [comment]
occasional state save + on exit sounds reasonable + it should be done not in worker threads but in either main or separate thread.
will likely scale better multithreading/multicpu wise, wont mess up caches of worker threads, will allow proper logic like "save every x seconds" and overall work more like actual checkpointing process should.
also checkpoint -> determseed should happen before spinning up worker threads, because otherwise worker threads will end up with same seeds on first iterations. which isn't too horrible, but, like, why not do it correct way?
regarding updating separate checkpoint variable: i kinda wanted logic of that separated from existing workers, because adding this stuff to worker code will add yet another thing to think about when looking at it, and it's already a mess.
regarding argument, '-c' just feels too common and this feels like kinda extra feature of extra feature so its very much uncommon. also yes keeping compatibility between releases is reasonable, why would I not do that?

**Comment by scribblemaniac** [comment]
This has been updated with the suggested changes.

**Comment by cathugger** [comment]
This now looks definitely much better. Nice :+1:
I will probably merge this and maybe improve functionality later if I feel like it.

**Comment by cathugger** [comment]
Hmm can see use of bool. That's not quite C99 iirc. Also memset for orig determ seed isnt needed in case no checkpoint was specified. Guess ill do some edits before merging.

**Comment by cathugger** [comment]
Also should maybe add self to acknowledgements section of readme.

**Comment by scribblemaniac** [comment]
> Hmm can see use of bool. That's not quite C99 iirc.

I believe stdbool.h is C99 and bool is defined in that.

>  Also memset for orig determ seed isnt needed in case no checkpoint was specified.

:+1:

**Comment by cathugger** [comment]
>I believe stdbool.h is C99 and bool is defined in that.

actually correct, i though it was newer than that.

**Pull request merged**
